# 博客基础信息
title: Hao的技术博客
description: 分享编程、技术与生活思考
baseurl: ""
url: "https://haoxstrong.github.io"
author: haoxstrong

# 主题与构建
remote_theme: cotes2020/chirpy
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

# 文章配置
permalink: /posts/:title/
paginate: 5
paginate_path: "/page/:num/"

# 主题特有配置
timezone: Asia/Shanghai
lang: zh-CN
